### ISSUE TITLE
extension Dictionary where Key == String, Value == Primitive {

### ISSUE THREAD

**Issue by lovemo** [OpenKitten/BSON#30]
extension Optional where Wrapped == Primitive {
                                 ^
/Users/Mac/Today-News-Admin/Packages/BSON-5.1.4/Sources/BSON/Interpreting.swift:204:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == String, Value == Primitive {
                               ^
/Users/Mac/Today-News-Admin/Packages/BSON-5.1.4/Sources/BSON/Interpreting.swift:204:49: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == String, Value == Primitive {
                                                ^
/Users/Mac/Today-News-Admin/Packages/BSON-5.1.4/Sources/BSON/Interpreting.swift:194:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == Primitive {
                              ^
/Users/Mac/Today-News-Admin/Packages/BSON-5.1.4/Sources/BSON/Document.swift:14:31: error: same-type requirement makes generic parameter 'Element' non-generic
extension Array where Element == Document {
                              ^
/Users/Mac/Today-News-Admin/Packages/BSON-5.1.4/Sources/BSON/Optional+BSON.swift:11:34: error: same-type requirement makes generic parameter 'Wrapped' non-generic
extension Optional where Wrapped == Primitive {
                                 ^
/Users/Mac/Today-News-Admin/Packages/BSON-5.1.4/Sources/BSON/Interpreting.swift:204:32: error: same-type requirement makes generic parameter 'Key' non-generic
extension Dictionary where Key == String, Value == Primitive {
                               ^
/Users/Mac/Today-News-Admin/Packages/BSON-5.1.4/Sources/BSON/Interpreting.swift:204:49: error: same-type requirement makes generic parameter 'Value' non-generic
extension Dictionary where Key == String, Value == Primitive {
                                                ^
<unknown>:0: error: build had 1 command failures

**Comment by Joannis** [comment]
Are you using Swift 3.0 or Swift 3.1?

**Comment by lovemo** [comment]
Swift version 3.0.1

**Comment by Joannis** [comment]
BSON 5 (MongoKitten 4) is designed for Swift 3.1 and above.

**Comment by Performat** [comment]
So does BSON 4 supports 3.0.1?

**Comment by Joannis** [comment]
Seriously? That's unexpected. 3.1 has been out for ages now. I can add 3.0 support, it's only one feature that relies on 3.1, but it's quite an important part of the API.

**Comment by Joannis** [comment]
BSON 4 supports Swift >= 3.0, so that'll work

**Comment by Joannis** [comment]
I'll be working on Swift 3.0 compatibility tomorrow
